name: business_card_scanner_app
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.15.0
  url_launcher: ^6.3.2
  contacts_service: ^0.6.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0